# Generated by Django 5.2.15 on 2026-06-14 02:52

import accounts.models
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('id_document', models.CharField(max_length=30, verbose_name='documento de identidad')),
                ('email', models.EmailField(max_length=254, verbose_name='correo de firma')),
                ('signature_image', models.ImageField(help_text='Imagen PNG (preferible con fondo transparente) o JPG.', upload_to=accounts.models.signature_image_path, validators=[accounts.validators.validate_signature_image], verbose_name='firma manuscrita')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='firma activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de firma',
                'verbose_name_plural': 'perfiles de firma',
            },
        ),
    ]
