# Generated by Django 5.2.15 on 2026-06-14 02:58

import django.db.models.deletion
import documents.models
import documents.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('original_file', models.FileField(upload_to=documents.models.original_pdf_path, validators=[documents.validators.validate_pdf], verbose_name='PDF original')),
                ('original_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='tamaño (bytes)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='páginas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('signed', 'Firmado'), ('voided', 'Anulado')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
