# Generated by Django 5.2.15 on 2026-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='placement_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='placement_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='placement_rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='placement_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='placement_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='placement_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
