# Generated by Django 5.2.15 on 2026-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_placement_h_document_placement_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qr_mode',
            field=models.CharField(choices=[('url', 'URL de verificación'), ('data', 'Datos de la firma (offline)')], default='url', max_length=4),
        ),
    ]
