# Generated by Django 5.2.15 on 2026-06-14 03:13

import django.db.models.deletion
import signing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_placement_h_document_placement_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=150)),
                ('signer_id_document', models.CharField(max_length=30)),
                ('signer_title', models.CharField(blank=True, max_length=150)),
                ('page_number', models.PositiveIntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('page_rotation', models.IntegerField(default=0)),
                ('signed_file', models.FileField(upload_to=signing.models.signed_pdf_path)),
                ('original_sha256', models.CharField(max_length=64)),
                ('signed_sha256', models.CharField(max_length=64)),
                ('verification_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('signed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('valid', 'Válida'), ('voided', 'Anulada')], db_index=True, default='valid', max_length=10)),
                ('void_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'firma',
                'verbose_name_plural': 'firmas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signed', 'Firmado'), ('voided', 'Anulado'), ('verified', 'Verificado'), ('downloaded', 'Descargado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('original_sha256', models.CharField(blank=True, max_length=64)),
                ('signed_sha256', models.CharField(blank=True, max_length=64)),
                ('verification_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='documents.document')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='signing.signature')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
