# Generated by Django 5.2.15 on 2026-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('signed', 'Firmado'), ('voided', 'Anulado'), ('verified', 'Verificado'), ('downloaded', 'Descargado')], max_length=20),
        ),
    ]
