# Generated by Django 5.2.15 on 2026-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_alter_auditevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='qr_mode',
            field=models.CharField(default='url', max_length=4),
        ),
    ]
